// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noqzawmirfqnlipmgadi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcXphd21pcmZxbmxpcG1nYWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzM5NDQsImV4cCI6MjA2NDY0OTk0NH0.qlg9TxLxpxRcxNs-H20w_Qp1tZY2EhJoEX1L42sJ5S0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);